### ISSUE TITLE
Mythtv plugin causes 5.0.3 on MX2 to go into a crash loop when activated

### ISSUE THREAD

**Issue by gnickoloff** [codesnake/OpenELEC.tv#48]
Installation of 5.0.3 on MX2 is uneventful and seems to be sucessful until Mythtv PVR plugin is activated. Then PVR/TV data is started to be downloaded from the Mythtv server, but Kodi crashes out after about 30-40 seconds and restarts multiple times for 30-40 seconds at a time (Incidentially, the Mythtv data download continues a little bit on each successive restart) until Mythtv locks up after about a dozen (or so) restarts.

**Comment by d0t101101** [comment]
Also having this issue with 5.0.3 on an MX2.  Running the latest MythTV backend v0.27.4+fixes.20150305 without other problems.  On my Windows/Linux PC installs of KODI, it works seamlessly.  On the MX2 & OpenELEC, it just hangs and restarts KODI when I try to enable live TV with the MythTV PVR addon. 

Will report back when I find a fix, but interested if anyone has any suggestions :)

Thanks!

**Comment by d0t101101** [comment]
Fixed by manually updating pvr.mythtv to the latest and greatest:

http://janbar.github.io/pvr.mythtv/download/index.html

Grab the 'OpenELEC-5.0 IMX6/ARM7' build, copy it to the MX2, and in KODI > Settings > Addons use 'install from zip'.  This will override the built in pvr.mythtv plugin.  Everything seems to be working great!

**Comment by gnickoloff** [comment]
Finally got a chance to try this out...
The above solution works! 
When I first encountered this problem, the updated version hadn't been released.
Thanks, d0t101101.
